### ISSUE TITLE
Add skill removal option

### ISSUE THREAD

**Issue by manthanchauhan** [manthanchauhan/online-portfolio#44]
- [x] On hovering over existing skills a dustbin icon should appear.
    * Make sure **NOT** to do this when hovering the "+" button.
    * Newly added skills should also have this feature, without requiring re-load.
    * For mobiles, we'll plan in a separate issue. We will think something with a long press.
- [x] Clicking on the dustbin should show a confirmation pop-up.
- [x] If the user clicks "yes", send an AJAX request to `"delete_skill"`.
- [x] In case of AJAX failure, show error modal used for error handling.
- [x] On success, the skill should get removed.
    * Just remove it from `skillMap`.
    * Set skill cell to `display:none`

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 can you complete the first task today?

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 I created the branch for your convenience.

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan 

I have implemented the part where on hovering over existing skills a dustbin icon should appear with other sub features expect mobile feature(which will be a different issue).

In second feature Popup should appear on clicking the delete button. Popup can be a modal/ promtbox/ etc. What you want pop-up to be when delete btn is clicked.

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 what are the subfeatures you are talking about? also just use the common [confirm()](https://www.w3schools.com/jsref/met_win_confirm.asp) for delete confirmation.

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan  Got it!!

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan   I have removed the skill from skillMap on clicking delete skill button. Please do the ajax request on delete_skill and rerendering!

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 please stop doing things, without being asked. This branch was meant to stop after completing dustbin hover.

Sorry! but to promote rules, will need to revert all your work!!

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan I have worked on only one feature now. Sorry to do work in advance. Please check the new commit.

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 merged the changes, now let's do the following:
1. Whenever the dustbin is clicked, it should trigger a confirm for whether the user really wants to delete the skill.
2. If the user selects "No", just return from the function immediately.
3. On "Yes", just do a console log, We'll add AJAX in the next subtask.

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 for this task, work on the branch "confirm-on-skill-delete".

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 I've added the ajax request, now we can move to the last task. Can you hide the skill cell after ajax request is successful? You just need to set the skill cell element to `display: none`.

**Comment by manthanchauhan** [comment]
Also, use the branch, "hide-skill-after-deletion"  for that.

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 [this](https://github.com/manthanchauhan/online-portfolio/blob/a31c747bfa1722acd1f01bde3844fb8b9a753143/online_portfolio/static/portfolio/js/edit.js#L677) is where you need to add the code, inside the `success` block.
