### ISSUE TITLE
Make Category Name editable

### ISSUE THREAD

**Issue by manthanchauhan** [manthanchauhan/online-portfolio#55]
- [x] Make Category name editable.
    * set `content-editable="true"`.
    * set a function on `onfocusout`.
    * Initial and final names of the category should be passed to the function.
    * max length of category name is 50.
        * function should do nothing if the length is > 50.
- [x] Implement character count.
    * character count should be visible while editing.
    * char count should become red, above 50.
- [x] Add AJAX call logic.
- [ ] On AJAX success, change the category name in whichever side required.

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 let's start on this one, once the delete skill feature is closed.

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 let's start on this one today, and aim to complete by tomorrow.

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 you can work on the first task, use the branch "cat-name-focus-out".

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 updated the task description.

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 you can work in the branch "update-cat-name-after-ajax", basically after ajax call, the value of the category name should be changed to the new name in the frontend (anywhere it was used ie, attributes, headings etc.)

**Comment by HarshitaAgarwal09** [comment]
I have worked on a cat-name-focus-out branch  and added, committed  and pushed the work on setting content-editable="true"

**Comment by HarshitaAgarwal09** [comment]
I have worked on a cat-name-focus-out branch and added, committed and pushed the work on setting a function on onfocusout.

**Comment by HarshitaAgarwal09** [comment]
I have worked on a cat-name-focus-out branch and added, committed, and pushed the work on setting Initial and final names of the category passed to the function named setCatName.

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan  Please explain the feature :
max length of category name is 50 and the function should do nothing if the length is > 50.

Which function are you talking about? 
Should I set this in setCatName function and I have to check the length of the new Category Name and then set up setCatName function to do nothing?

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 I've already completed the first three tasks (they're marked for some reason), you had to do the last task.

**> @HarshitaAgarwal09 you can work in the branch "update-cat-name-after-ajax", basically after ajax call, the value of the category name should be changed to the new name in the frontend (anywhere it was used ie, attributes, headings etc.)**

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan  ok

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan Please commit those tasks so that I can pull the latest codes!

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan There is a lot of repeated tasks I had to do. How will I work if the code is not updated to the latest features? Please do consider it !!

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan  On AJAX success, change the category name in every associated slides is completed.

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan Please assign the next task

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan  I have to work on this last task. Right?

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan I have completed the task
