### ISSUE TITLE
Delete error on default skills

### ISSUE THREAD

**Issue by manthanchauhan** [manthanchauhan/online-portfolio#79]
- [x] Pass a boolean `areSkillsDefault` from backend.
    * if `arSkillsDefault` is `True`, this means **all** the visible skills are default skills.
    * if `areSkillsDefault` is `False`, this means **none** of the visible skills is a default skill.
- [x] For default skills, remove the dustbin and show a tooltip on hover (*Open to suggestions*).
    * The tooltip should have the text:
        > Once you add a skill, these default skills will go away. 
- [x] When adding a new skill:
    1. After ajax success.
    2. If `areSkillsDefault` is `True`, **reset** the `skillMap` (*this will delete all default skills from frontend*).
    3. Add the new skill to the `skillMap`.
    4. Re-render the skills (*already happening*).

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 Let's work on this issue now. So as you may know, for every new user, we show some default skills in his portfolio just as an example. But there is a bug, on hovering over those default skills the delete dustbin appears (keep in mind that these skills do not exist in the DB, there are mere for representation). So naturally, attempting to delete these default skills, shows the user an error "Skill does not exist", which does not make sense to a new user.

So, we have to remove dustbin from these default skills and rather show a tooltip explaining that, "Once you add a skill, these default skills will definitely go away".

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 If you read the issue description, I have already added a boolean to decide whether the skills received from the backend are default, or genuine, you can now proceed to the next task.

**Comment by manthanchauhan** [comment]
@HarshitaAgarwal09 work on the branch ` add-tooltip-for-default-skills`.

**Comment by HarshitaAgarwal09** [comment]
@manthanchauhan  Okay, will work on it
